# Generated by Django 3.2.7 on 2022-03-31 03:26

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Passenger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('nationality', models.CharField(choices=[('Nepali', 'Nepali'), ('Indian', 'Indian'), ('Foreign', 'Foreign')], max_length=100)),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None)),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('airline', models.CharField(max_length=100)),
                ('pnr', models.CharField(max_length=10)),
                ('flight_number', models.CharField(max_length=100)),
                ('sector', models.CharField(max_length=10)),
                ('flight_date', models.DateField()),
                ('flight_time', models.TimeField()),
                ('expires_on', models.DateTimeField()),
                ('class_name', models.CharField(max_length=100, null=True)),
                ('booked_on', models.DateTimeField(auto_now_add=True)),
                ('ticketed', models.BooleanField(default=False)),
                ('unit_price', models.IntegerField(null=True)),
                ('passengers', models.ManyToManyField(blank=True, to='api.Passenger')),
            ],
        ),
    ]
