# Generated by Django 3.2.7 on 2022-04-02 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('private', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('airline', models.CharField(max_length=100)),
                ('pnr', models.CharField(max_length=10)),
                ('flight_number', models.CharField(max_length=100)),
                ('sector', models.CharField(max_length=10)),
                ('flight_date', models.DateField()),
                ('flight_time', models.TimeField()),
                ('expires_on', models.DateTimeField()),
                ('class_name', models.CharField(max_length=100, null=True)),
                ('booked_on', models.DateTimeField(auto_now_add=True)),
                ('ticketed', models.BooleanField(default=False)),
                ('nop', models.IntegerField(null=True)),
                ('unit_price', models.IntegerField(null=True)),
                ('passengers', models.ManyToManyField(blank=True, to='private.Customer')),
            ],
        ),
    ]
