# Generated by Django 3.2.7 on 2022-04-02 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('private', '0005_auto_20220402_2311'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='location',
        ),
    ]
