# Generated by Django 3.2.7 on 2022-04-02 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('private', '0006_remove_customer_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bill',
            name='customer',
        ),
    ]
