# Generated by Django 3.2.7 on 2022-04-02 18:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('private', '0007_remove_bill_customer'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerID',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cid', models.CharField(max_length=150)),
            ],
        ),
        migrations.AddField(
            model_name='customer',
            name='cid',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='private.customerid'),
        ),
    ]
