# Generated by Django 3.2.7 on 2022-04-03 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('private', '0008_auto_20220402_2351'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerid',
            name='cid',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
