# Generated by Django 3.2.7 on 2022-04-06 18:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('private', '0010_auto_20220406_2353'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='pnr',
        ),
        migrations.CreateModel(
            name='BookingTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='private.booking')),
                ('ticket', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='private.ticket')),
            ],
        ),
    ]
