# Generated by Django 3.2.7 on 2022-04-06 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('private', '0011_auto_20220406_2357'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='type',
            field=models.CharField(choices=[('Adult', 'Adult'), ('Child', 'Child')], max_length=100, null=True),
        ),
    ]
