# Generated by Django 3.2.7 on 2022-04-06 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('private', '0012_alter_customer_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Airline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='booking',
            name='airline',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='airlines',
        ),
        migrations.AddField(
            model_name='booking',
            name='airline',
            field=models.ManyToManyField(to='private.Airline'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='airlines',
            field=models.ManyToManyField(to='private.Airline'),
        ),
    ]
