# Generated by Django 3.2.7 on 2022-04-06 18:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('private', '0013_auto_20220407_0018'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='airlines',
        ),
        migrations.AddField(
            model_name='ticket',
            name='airlines',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='private.airline'),
        ),
    ]
