# Generated by Django 3.2.7 on 2022-04-06 18:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('private', '0014_auto_20220407_0021'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='airline',
        ),
        migrations.AddField(
            model_name='booking',
            name='airline',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='private.airline'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='passenger_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='private.customer'),
        ),
    ]
