# Generated by Django 3.2.7 on 2022-04-06 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('private', '0015_auto_20220407_0030'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='pnr',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
