# Generated by Django 3.2.7 on 2022-04-06 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('private', '0016_ticket_pnr'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='name',
            field=models.CharField(max_length=500, null=True, unique=True),
        ),
    ]
