# Generated by Django 3.2.7 on 2022-04-07 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('private', '0017_alter_customer_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='expires_on',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='flight_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='flight_number',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='flight_time',
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='passengers',
            field=models.ManyToManyField(blank=True, null=True, to='private.Customer'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='pnr',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='sector',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
