# Generated by Django 3.2.7 on 2022-04-07 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('private', '0019_auto_20220407_1026'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='unit_price_currency',
        ),
        migrations.AlterField(
            model_name='booking',
            name='unit_price',
            field=models.IntegerField(null=True),
        ),
    ]
