# Generated by Django 3.2.7 on 2022-04-07 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('private', '0020_auto_20220407_1036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='pnr',
            field=models.CharField(max_length=10, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='pnr',
            field=models.CharField(max_length=10, null=True, unique=True),
        ),
    ]
