# Generated by Django 3.2.7 on 2022-04-09 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('private', '0022_auto_20220409_1125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='pnr',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.DeleteModel(
            name='BookingTicket',
        ),
    ]
