# Generated by Django 3.2.7 on 2022-04-09 06:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('private', '0025_commission'),
    ]

    operations = [
        migrations.RenameField(
            model_name='commission',
            old_name='commisson',
            new_name='commission',
        ),
        migrations.RenameField(
            model_name='commission',
            old_name='commisson_currency',
            new_name='commission_currency',
        ),
    ]
